name: Generate RSS Feeds

on:
  schedule:
    - cron: '0 * * * *'  # 매 1시간마다 실행
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate RSS feeds
      run: python rss_generator.py

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add rss/*.xml
        git commit -m "Update RSS feeds" || echo "No changes to commit"
        git push
